### ISSUE TITLE
DB2 Setup fails at prerequisites check

### ISSUE THREAD

**Issue by Flor-IT** [bernardoVale/ansible-role-db2#25]
Hi,
I´m using your role with ansible-playbook v2.0.1.0. It fails at prerequisites check with message

```
fatal: [devvm-centos7]: FAILED! => {"failed": true, "msg": "The conditional check ''failed' in precheck.stderr' failed. The error was: error while evaluating conditional ('failed' in precheck.stderr): Unable to look up a name or access an attribute in template string. Make sure your variable name does not contain invalid characters like '-'."}
```

Do I have to setup a variable or is this just a syntax failure in "failed_when". I´m new to ansible so I´m not able to figure it out myself.

Thanks for the role!

**Comment by bernardoVale** [comment]
Hello @Flor-IT, no you don't have to setup this variable. This is done with the [`register`](http://docs.ansible.com/ansible/playbooks_variables.html#registered-variables) clause

I think I know the error you are getting.

If you check my code [here](https://github.com/bernardoVale/ansible-role-db2/blob/master/tasks/main.yml) **line 25** you will see that I'm guessing that the compressed DB2 binary will create a folder called `server`.

At the time that I was developing that role I thought every DB2 binary created this same folder but now I know that are some variations, like `server_t`. 

Your playbook is failing because ansible is trying to access a folder that doesn't exists and I think that the variable `precheck` even get created.

Please make sure your compressed DB2 file are indeed creating a `server` folder.

I will try to implement something to deal with this situation. 

You can also change the hardcoded `server`. Just change those files:
1. [main.yml](https://github.com/bernardoVale/ansible-role-db2/blob/master/tasks/main.yml)
2. [get_db2.yml](https://github.com/bernardoVale/ansible-role-db2/blob/master/tasks/get_db2.yml)

change where is `server` for the folder name that the compressed file it's generating.

**Comment by bernardoVale** [comment]
Hi @Flor-IT , I've changed the code and now you can change the variable `db2_creates` to change the DB2 binary folder. Could you give it a try with the latest code? Check [this example](https://github.com/bernardoVale/ansible-role-db2/tree/master/examples/db2_express-c_example.yml).

**Comment by Flor-IT** [comment]
Thanks! Works now with "server_t"
